/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;


public class KetQuaPhanLopForm extends javax.swing.JFrame {

    /**
     * Creates new form TrichChon
     */
    public KetQuaPhanLopForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("KẾT QUẢ PHÂN LOẠI");

        table.setFont(new Font("Times New Roman", Font.PLAIN, 15)); // NOI18N
        table.setModel(new DefaultTableModel(
        	new Object[][] {
        			
        			{"1", "0.107753 ", "1", "0.135984", "IF(x3=9;x23=4;x29=0;x30=0;x32=0;x34=0;x35=0) THEN(y=1); "},
        			{"2", "0.091026 ", "1 ", "0.114876", "IF(x3=11;x23=1;x29=0;x30=0;x32=0;x34=0;x35=0) THEN(y=1);"},
        			{"3", "0.014018 ", "1", "0.067519", "IF(x3=11;x23=0;x29=0;x30=0;x32=0;x34=4;x35=0) THEN(y=0);"},
        			{"4", "0.004901 ", "1 ", "0.023605", "IF(x3=10;x23=0;x29=0;x30=0;x32=0;x34=0;x35=4) THEN(y=0);"},
        			{"5", "0.460138 ", "0.999248", "0.580696", "IF(x3=9;x23=0;x29=0;x30=0;x32=0;x34=0;x35=0) THEN(y=1); "},
        			{"6", "0.087452 ", "0.962183", "0.421234", "IF(x3=0;x23=0;x29=0;x30=0;x32=0;x34=0;x35=0) THEN(y=0); "},
        			{"7", "0.101457 ", "0.999781", "0.128039", "IF(x3=11;x23=2;x29=0;x30=0;x32=0;x34=0;x35=0) THEN(y=1);"},
        			{"8", "0.015149 ", "0.974479", "0.07297 ", "IF(x3=0;x23=0;x29=0;x30=0;x32=1;x34=0;x35=0) THEN(y=0); "},
        			{"9", "0.008271 ", "0.975645", "0.039839", "IF(x3=0;x23=0;x29=0;x30=0;x32=2;x34=0;x35=0) THEN(y=0); "},
        			{"10","0.004012 ", "0.998992", "0.019325", "IF(x3=0;x23=0;x29=0;x30=0;x32=0;x34=4;x35=0) THEN(y=0); "},

        	},
        	new String[] {
        		"S\u1ED1 t\u1EE9 t\u1EF1", "\u0110\u1ED9 h\u1ED7 tr\u1EE3", "\u0110\u1ED9 ch\u00EDnh x\u00E1c", "\u0110\u1ED9 b\u1EA3o ph\u1EE7", "Lu\u1EADt"
        	}
        ) {
        	Class[] columnTypes = new Class[] {
        		Object.class, String.class, Object.class, Object.class, Object.class
        	};
        	public Class getColumnClass(int columnIndex) {
        		return columnTypes[columnIndex];
        	}
        });
        table.getColumnModel().getColumn(0).setPreferredWidth(80);
        table.getColumnModel().getColumn(1).setPreferredWidth(80);
        table.getColumnModel().getColumn(2).setPreferredWidth(80);
        table.getColumnModel().getColumn(3).setPreferredWidth(80);
        table.getColumnModel().getColumn(4).setPreferredWidth(400);
		DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
		centerRenderer.setHorizontalAlignment(JLabel.CENTER);
		table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
		table.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
		table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
		table.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
		for (int i=0 ; i<10 ; i++) {
			table.setRowHeight(i, 25);
		}
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetQuaPhanLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetQuaPhanLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetQuaPhanLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetQuaPhanLopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KetQuaPhanLopForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
