/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.constant.GeneralConstant;
import com.kddcup.KddCupUtils;
import com.model.DosObject;
import com.model.ShortDOSObject;
import com.model.ThresholdObject;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

public class MainForm extends JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tienxulyPane = new JPanel();
        jScrollPane1 = new JScrollPane();
        tienXulyTable = new JTable();
        jLabel2 = new JLabel();
        titleLabel = new JLabel();
        prepareDataBotton = new JButton();
        generalRule = new JButton();
        resultClassifyBotton = new JButton();
        otherButton = new JButton();

        tienXulyTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tienXulyTable.setModel(new DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Service", "Count", "Srv_serror_rate", "Srv_rerror_rate", "Dst_host_count", "Dst_host_same_srv_rate", "Dst_host_diff_srv_rate", "Attack"
            }
        ));
        jScrollPane1.setViewportView(tienXulyTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Kết quả tiền xử lý dữ liệu");

        GroupLayout tienxulyPaneLayout = new GroupLayout(tienxulyPane);
        tienxulyPane.setLayout(tienxulyPaneLayout);
        tienxulyPaneLayout.setHorizontalGroup(
            tienxulyPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tienxulyPaneLayout.createSequentialGroup()
                .addGroup(tienxulyPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tienxulyPaneLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel2))
                    .addGroup(tienxulyPaneLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 819, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        tienxulyPaneLayout.setVerticalGroup(
            tienxulyPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, tienxulyPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 279, GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 0, 0));
        titleLabel.setText("NGHIÊN CỨU ỨNG DỰNG KỸ THUẬT TẬP THÔ TRONG PHÂN LỚP DỮ LIỆU");

        prepareDataBotton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prepareDataBotton.setForeground(new java.awt.Color(0, 0, 153));
        prepareDataBotton.setText("TIỀN XỬ LÝ DỮ LIỆU");
        prepareDataBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prepareDataActionPerformed(evt);
            }
        });

        generalRule.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        generalRule.setForeground(new java.awt.Color(0, 0, 153));
        generalRule.setText("SINH LUẬT QUYẾT ĐỊNH");
        generalRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalRuleActionPerformed(evt);
            }
        });

        resultClassifyBotton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resultClassifyBotton.setForeground(new java.awt.Color(51, 0, 0));
        resultClassifyBotton.setText("KHÁC");

        otherButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        otherButton.setForeground(new java.awt.Color(0, 0, 102));
        otherButton.setText("KẾT QUẢ PHÂN LỚP");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(prepareDataBotton, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherButton, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(generalRule, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultClassifyBotton, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(titleLabel, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(prepareDataBotton, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
                    .addComponent(generalRule, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(otherButton, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultClassifyBotton, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prepareDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prepareDataActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File file = fc.getSelectedFile();
        if (file == null) {
            System.out.println("Không chọn file");
            return;
        }
        
        List<ShortDOSObject> shortKddCups = new ArrayList<ShortDOSObject>();
        List<DosObject> kddCups = new ArrayList<DosObject>();
        List<String> services = new ArrayList<String>();
        ThresholdObject threshold = new ThresholdObject();
        Set<String> attack = new HashSet<String>();
        BufferedReader buffReader = null;
        try {
            buffReader = new BufferedReader(new InputStreamReader(
                    new FileInputStream(file),
                    GeneralConstant.ENCODING_UTF8));
            String token;
            while ((token = buffReader.readLine()) != null) {
                String[] parameters = token.split(",");
                if (parameters.length == 42) {
                    ShortDOSObject shortKddCup = new ShortDOSObject();
                    float count;
                    float srvSerrorRate;
                    float srvRerrorRate;
                    float dstHostCount;
                    float dstHostSameSrvRate;
                    float dstHostDiffSrvRate;

                    String service = parameters[2];
                    if (!services.contains(service)) {
                        services.add(service);
                    }
                    int index = services.indexOf(service);
                    shortKddCup.setService(index + "");

                    count = Float.parseFloat(parameters[22]);
                    threshold.setCount(count);
                    shortKddCup.setCount(count);

                    srvSerrorRate = Float.parseFloat(parameters[28]);
                    threshold.setSrvSerrorRate(srvSerrorRate);
                    shortKddCup.setSrvSerrorRate(srvSerrorRate);

                    srvRerrorRate = Float.parseFloat(parameters[29]);
                    threshold.setSrvRerrorRate(srvRerrorRate);
                    shortKddCup.setSrvRerrorRate(srvRerrorRate);

                    dstHostCount = Float.parseFloat(parameters[31]);
                    threshold.setDstHostCount(dstHostCount);
                    shortKddCup.setDstHostCount(dstHostCount);

                    dstHostSameSrvRate = Float.parseFloat(parameters[33]);
                    threshold.setDstHostSameSrvRate(dstHostSameSrvRate);
                    shortKddCup.setDstHostSameSrvRate(dstHostSameSrvRate);

                    dstHostDiffSrvRate = Float.parseFloat(parameters[34]);
                    threshold.setDstHostDiffSrvRate(dstHostDiffSrvRate);
                    shortKddCup.setDstHostDiffSrvRate(dstHostDiffSrvRate);

                    String label = parameters[41].replace(".", "");
                    attack.add(label);
                    if (GeneralConstant.DOS_LABELS.contains(label)) {
                        label = "1";
                    } else {
                        label = "0";
                    }
                    shortKddCup.setAttack(label);
                    shortKddCups.add(shortKddCup);
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (buffReader != null) {
                try {
                    buffReader.close();
                } catch (IOException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        // for (String ob : attack) {
        // System.out.println(ob);
        // }
        System.out.println("Min: " + threshold.getCountMin() + ", Max: "
                + threshold.getCountMax());
        System.out.println("Min: " + threshold.getSrvSerrorRateMin()
                + ", Max: " + threshold.getSrvSerrorRateMax());
        System.out.println("Min: " + threshold.getSrvRerrorRateMin()
                + ", Max: " + threshold.getSrvRerrorRateMax());
        System.out.println("Min: " + threshold.getDstHostCountMin() + ", Max: "
                + threshold.getDstHostCountMax());
        System.out.println("Min: " + threshold.getDstHostSameSrvRateMin()
                + ", Max: " + threshold.getDstHostSameSrvRateMax());
        System.out.println("Min: " + threshold.getDstHostDiffSrvRateMin()
                + ", Max: " + threshold.getDstHostDiffSrvRateMax());

        for (ShortDOSObject ob : shortKddCups) {
            DosObject temp = new DosObject();
            temp.setX3(Integer.parseInt(ob.getService()));
            temp.setX23(KddCupUtils.getInstance().fetchUniNumber(
                    threshold.getCountMin(), threshold.getCountMax(),
                    GeneralConstant.NUMBER_OF_RANGES, ob.getCount()));
            temp.setX29(KddCupUtils.getInstance().fetchUniNumber(
                    threshold.getSrvSerrorRateMin(),
                    threshold.getSrvSerrorRateMax(),
                    GeneralConstant.NUMBER_OF_RANGES, ob.getSrvSerrorRate()));
            temp.setX30(KddCupUtils.getInstance().fetchUniNumber(
                    threshold.getSrvRerrorRateMin(),
                    threshold.getSrvRerrorRateMax(),
                    GeneralConstant.NUMBER_OF_RANGES, ob.getSrvRerrorRate()));
            temp.setX32(KddCupUtils.getInstance().fetchUniNumber(
                    threshold.getDstHostCountMin(),
                    threshold.getDstHostCountMax(),
                    GeneralConstant.NUMBER_OF_RANGES, ob.getDstHostCount()));
            temp.setX34(KddCupUtils.getInstance().fetchUniNumber(
                    threshold.getDstHostSameSrvRateMin(),
                    threshold.getDstHostSameSrvRateMax(),
                    GeneralConstant.NUMBER_OF_RANGES,
                    ob.getDstHostSameSrvRate()));
            temp.setX35(KddCupUtils.getInstance().fetchUniNumber(
                    threshold.getDstHostDiffSrvRateMin(),
                    threshold.getDstHostDiffSrvRateMax(),
                    GeneralConstant.NUMBER_OF_RANGES,
                    ob.getDstHostDiffSrvRate()));
            temp.setX42(Integer.parseInt(ob.getAttack()));
            kddCups.add(temp);
        }
        FileWriter writer = null;
        try {
            writer = new FileWriter(
                    GeneralConstant.INPUT_KDD_CUP_10_PERCENT_8_PARAMESTER_DOS);
            for (DosObject ob : kddCups) {
                writer.write(ob.toString() + "\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (writer != null) {
                try {
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        this.tienxulyPane.setVisible(true);
        this.tienxulyPane.show();
    }//GEN-LAST:event_prepareDataActionPerformed

    private void generalRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalRuleActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_generalRuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton generalRule;
    private JLabel titleLabel;
    private JLabel jLabel2;
    private JScrollPane jScrollPane1;
    private JButton otherButton;
    private JButton prepareDataBotton;
    private JButton resultClassifyBotton;
    private JTable tienXulyTable;
    private JPanel tienxulyPane;
    // End of variables declaration//GEN-END:variables
}
