/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Manh Son
 */
public class SinhLuatQuyetDinhForm extends javax.swing.JFrame {

    /**
     * Creates new form TrichChon
     */
    public SinhLuatQuyetDinhForm() {
    	setTitle("Form sinh luật quyết định");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("SINH LUẬT QUYẾT ĐỊNH");

        table.setFont(new Font("Times New Roman", Font.PLAIN, 15)); // NOI18N
        table.setModel(new DefaultTableModel(
        	new Object[][] {
        		{new Integer(1), "IF(x3=1;x23=0;x29=0;x30=0;x32=0;x34=3;x35=0) THEN(y=0);"},
        		{new Integer(2), "IF(x3=11;x23=0;x29=0;x30=0;x32=0;x34=0;x35=0) THEN(y=0);"},
        		{new Integer(3), "IF(x3=11;x23=0;x29=0;x30=0;x32=0;x34=0;x35=1) THEN(y=0);"},
        		{new Integer(4), "IF(x3=59;x23=0;x29=0;x30=0;x32=3;x34=0;x35=0) THEN(y=0);"},
        		{new Integer(5), "IF(x3=11;x23=0;x29=0;x30=0;x32=0;x34=3;x35=2) THEN(y=1);"},
        		{new Integer(6), "IF(x3=1;x23=0;x29=0;x30=0;x32=0;x34=3;x35=2) THEN(y=0);"},
        		{new Integer(7), "IF(x3=54;x23=2;x29=0;x30=0;x32=0;x34=0;x35=0) THEN(y=1);"},
        		{new Integer(8), "IF(x3=11;x23=0;x29=0;x30=0;x32=0;x34=0;x35=2) THEN(y=0);"},
        		{new Integer(9), "IF(x3=0;x23=2;x29=0;x30=0;x32=0;x34=0;x35=0) THEN(y=1);"},
        		{new Integer(10), "IF(x3=0;x23=0;x29=0;x30=0;x32=3;x34=3;x35=0) THEN(y=0);"},
        		{new Integer(11), "IF(x3=10;x23=0;x29=0;x30=0;x32=3;x34=0;x35=0) THEN(y=0);"},
        		{new Integer(12), "IF(x3=1;x23=0;x29=0;x30=0;x32=0;x34=3;x35=3) THEN(y=0);"},
        		{new Integer(13), "IF(x3=11;x23=0;x29=0;x30=0;x32=0;x34=3;x35=1) THEN(y=1);"},
        		{new Integer(14), "IF(x3=61;x23=0;x29=2;x30=3;x32=0;x34=0;x35=0) THEN(y=0);"},
        		{new Integer(15), "IF(x3=42;x23=1;x29=0;x30=2;x32=0;x34=0;x35=1) THEN(y=0);"},
        	},
        	new String[] {
        		"S\u1ED1 th\u1EE9 t\u1EF1", "Lu\u1EADt quy\u1EBFt \u0111\u1ECBnh"
        	}
        ) {
        	Class[] columnTypes = new Class[] {
        		Integer.class, String.class
        	};
        	public Class getColumnClass(int columnIndex) {
        		return columnTypes[columnIndex];
        	}
        	boolean[] columnEditables = new boolean[] {
        		false, true
        	};
        	public boolean isCellEditable(int row, int column) {
        		return columnEditables[column];
        	}
        });
        for (int i=0 ; i<14 ; i++) {
			table.setRowHeight(i, 25);
		}
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(800);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
		centerRenderer.setHorizontalAlignment(JLabel.CENTER);
		table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
//		table.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(310)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(67)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 722, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 414, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(41, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhLuatQuyetDinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhLuatQuyetDinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhLuatQuyetDinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhLuatQuyetDinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhLuatQuyetDinhForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
